### ISSUE TITLE
Crash when launching game

### ISSUE THREAD

**Issue by MechWarrior99** [PaleoCrafter/VanillaImmersion#1]
Hello,
I'm not sure if this is due to me using the wrong version of something or if it is a real bug.

**Important Information**

* Minecraft 1.9.4
* Forge 12.17.0.1909
* Vanilla Immersion 0.0.1.0

**Crash Report**
[Crash](http://pastebin.com/T8ZThSrd)

**Comment by PaleoCrafter** [comment]
Thanks a lot for reporting this issue. It appears that the automatic upload to CurseForge does not reobfuscate the mod, I forgot a simple `reobf` prefix in the buildscript. I only tried the build I upload here on GitHub and that worked just fine (it uses another Gradle task). I will fix this immediately and push out Version 0.0.1.1.

**Comment by PaleoCrafter** [comment]
Just as an update: That commit did in fact not fix the issue, but I have actually fixed it in my local copy and just pushed the build. Turns out, either I'm too stupid to properly deal with Gradle or you really have to do get the CurseForge plugin to pick up the fat jar in a roundabout way.

**Comment by MechWarrior99** [comment]
Just downloaded the new version and it works fine :)
