### ISSUE TITLE
Crash after selecting an item with the "?" button

### ISSUE THREAD

**Issue by Irdes** [PaleoCrafter/VanillaImmersion#10]
Crash report: https://pastebin.com/02B761Jf

Steps to reproduce:
1) Craft and put down and immersive crafting table
2) Press the ? button on it
3) Select desired item (stone pickaxe in my case)
???
Crash

**Comment by PaleoCrafter** [comment]
This is due to a change in JEI's API. I don't maintain the 1.10.2 version of this mod anymore, but this will be fixed in 1.12.
