### ISSUE TITLE
Missing Forgelin message/crash

### ISSUE THREAD

**Issue by rckymtnrfc** [PaleoCrafter/VanillaImmersion#13]
I'm getting a message on the client and a crash on the server stating Vanilla Immersion requires Forgelin 1.5.0.

I've got Forgelin 1.5.0.  I even re-downloaded it and replaced it in case I had a corrupt version.  Unfortunately I'm still seeing the same thing.

Vanilla Immersion 1.12-1.1.2.3
Forgelin 1.5.0
Forge 2415

**Comment by PaleoCrafter** [comment]
This issue appears to be on Forgelin's side, version 1.5.0 on CF and the Maven still are 1.4.2 in the @Mod annotation. I'll get a fix to Forgelin and release a version of VI that doesn't depend on a given version of Forgelin for now.
