### ISSUE TITLE
Missing Mods

### ISSUE THREAD

**Issue by coolyear123** [PaleoCrafter/VanillaImmersion#15]
I installed the required library and have the latest version of forge but upon startup minecraft says "Vanilla Immersion is missing mods it depends on. Include the following mods or remove Vanilla Immersion. Forge 14.21.1.2426"

**Comment by PaleoCrafter** [comment]
I can't reproduce this with a fresh installation of Forge 14.21.1.2426 and Forgelin 1.5.1. Make sure you actually got the right Forge build (latest, *not* recommended!). The installer can be found on the [files site](http://adfoc.us/serve/sitelinks/?id=271228&url=http://files.minecraftforge.net/maven/net/minecraftforge/forge/1.12-14.21.1.2426/forge-1.12-14.21.1.2426-installer-win.exe).

**Comment by coolyear123** [comment]
Still a problem. [image1.JPG]

Sincerely: Daniel Petit

On Jul 28, 2017, at 2:53 PM, Marvin Rösch <notifications@github.com<mailto:notifications@github.com>> wrote:


I can't reproduce this with a fresh installation of Forge 14.21.1.2426 and Forgelin 1.5.1. Make sure you actually got the right Forge build (latest, not recommended!). The installer can be found on the files site<http://adfoc.us/serve/sitelinks/?id=271228&url=http://files.minecraftforge.net/maven/net/minecraftforge/forge/1.12-14.21.1.2426/forge-1.12-14.21.1.2426-installer-win.exe>.
