### ISSUE TITLE
Furnace not working only on server

### ISSUE THREAD

**Issue by davqvist** [PaleoCrafter/VanillaImmersion#16]
MC 1.12
Forge 2426 (I know a bit outdated, will update soon)
VI 2.0.2.0

Everything seems to work fine in singleplayer, but I started a server yesterday and you couldn't interact with the Furnace at all, right clicking stuff had no effect.

**Comment by PaleoCrafter** [comment]
Are you sure you're running Forge 2416 and not 2426? That version is what the mod strictly depends on, as it addresses the registry override issue. If you're able to run the game in an outdated version, I'll have to look into my dependency checking.

**Comment by davqvist** [comment]
Sorry, typo, yes 2426
