### ISSUE TITLE
Map isn't scaling

### ISSUE THREAD

**Issue by SoldierKucha** [PaleoCrafter/VanillaImmersion#17]
Vanilla map not scaling if crafted on Immersive Workbench :( After adding paper it stays on 1:1 scale.

**Comment by marvin-roesch** [comment]
Hm, what other mods are you using, what version of the mod and Forge? The workbench directly uses Vanilla behaviour, so I see no reason for it to not work properly.

**Comment by SoldierKucha** [comment]
Forge 14.21.1.2443 
![image](https://user-images.githubusercontent.com/15803655/29216709-37931d20-7eb8-11e7-9a91-3cceeb249061.png)

**Comment by SoldierKucha** [comment]
bibliocrafts Fancy Workbench scale map properly
