### ISSUE TITLE
[1.12.1] Items are consumed, which should get damaged instead.

### ISSUE THREAD

**Issue by MasterEnderman** [PaleoCrafter/VanillaImmersion#18]
I've created some Recipes with CraftTweaker, where a tool gets damaged during the crafting process. If I try to craft the recipe on a Vanilla Immersion Crafting Table the tool, which should get damaged is consumed instead. In the Player Inventory everything works fine, I guess the recipe isn't the issue.

Minecraft: 1.12.1
Forge: 14.22.0.2467
Vanilla Immersion: 2.0.3.4

**Comment by marvin-roesch** [comment]
Similar to #19, try using version [2.0.2.4](https://minecraft.curseforge.com/projects/vanilla-immersion/files/2466357) of the mod, then report back whether the issue still occurs since I should have fixed it since.

**Comment by MasterEnderman** [comment]
After testing it with the new version this doesn't happen anymore. Thanks for fixing it.
