### ISSUE TITLE
Crafting grid not updating

### ISSUE THREAD

**Issue by MechWarrior99** [PaleoCrafter/VanillaImmersion#2]
Hi,
I think I found a bug with the crafting table grid. Here's the in-depth of the issue...

Important Information

* Minecraft 1.9.4
* Forge 12.17.0.1909
* Vanilla Immersion 0.0.1.1

Description
While putting items on the grid of the crafting table if it finds a valid recipe with the current pattern of items it will display the output for that item and will not update, and once you are done placing all your items and left click the output you will get the other item that is displayed and not the one that is on the grid it self.

Screanshots
![2016-05-21_07 34 55](https://cloud.githubusercontent.com/assets/8076495/15449034/6386bb7c-1f27-11e6-8e85-50b982aff595.png)
![2016-05-21_07 35 06](https://cloud.githubusercontent.com/assets/8076495/15449035/66544914-1f27-11e6-943e-0f1818e0ab8b.png)
![2016-05-21_07 35 21](https://cloud.githubusercontent.com/assets/8076495/15449036/67eec8ee-1f27-11e6-8007-6c4d3e0f548e.png)
![2016-05-21_07 36 11](https://cloud.githubusercontent.com/assets/8076495/15449037/69c9c826-1f27-11e6-9594-f4b0deb698c2.png)
![2016-05-21_07 36 22](https://cloud.githubusercontent.com/assets/8076495/15449038/6b736fd8-1f27-11e6-97b1-ed15e742de2a.png)

**Comment by PaleoCrafter** [comment]
Thanks for reporting yet another issue! I've changed the method that gets the result of the current recipe in the last version and only tried it with the same recipe all the time, so I didn't notice the obvious bug. Should be fixed with the next version.
