### ISSUE TITLE
Crush when i try to disable an option

### ISSUE THREAD

**Issue by Ricciolo2001** [PaleoCrafter/VanillaImmersion#20]
When i open the config and i try to change the option to disable the real furnace or the other options the game crush

**Comment by marvin-roesch** [comment]
When exactly does the game crash? As soon as you change an option or only when you restart the game? Could you provide me with a full crash report, since I cannot reproduce this issue locally.

**Comment by ThugPug43** [comment]
https://paste.dimdev.org/ebinozewej.mccrash This is a crash report of that very thing. For some odd reason I cannot see the little images on the beacon, so I tried to disable it and this happened.
