### ISSUE TITLE
WHAAAAA??????

### ISSUE THREAD

**Issue by DerpyCoder21** [PaleoCrafter/VanillaImmersion#21]
this is what it said: Needs: "forge 14.21.1.2426" Or Above. WHAT DOES THAT EVEN MEAN? im using 1.12 not 1.12.2

**Comment by DerpyCoder21** [comment]
☻/ This is bob. Copy and paste him so he can take over GitHub.
/▌
/\

**Comment by DerpyCoder21** [comment]
wait what... oh no. HES BACK!

**Comment by marvin-roesch** [comment]
👌
