### ISSUE TITLE
im sorry.

### ISSUE THREAD

**Issue by DerpyCoder21** [PaleoCrafter/VanillaImmersion#22]
i didint mean to use bob. but please what does it mean? i dont get it!

**Comment by DerpyCoder21** [comment]
i just want to find out WHAT Forge 1298473486937289756723648576234 means!

**Comment by marvin-roesch** [comment]
Forge 1298473486937289756723648576234 in particular is a build of Forge that doesn't exist yet and will probably take quite some time to arrive, considering we haven't even gotten to the order of magnitude of 10^5. As a rule of thumb, however, the mod depends on some (existing) version of Minecraft Forge and hence "forces" you to update to at least that indicated version.

As it's apparently asking for build 1298473486937289756723648576234, you'll either have to wait a couple of years for that version to be released or switch to a version of the mod that depends on a more recent, reasonable version of Forge. In general, the mod should run fine with whatever is considered 'latest' for Minecraft version 1.12(.2).

**Comment by marvin-roesch** [comment]
As an aside: It was very careless of you to invoke Bob so nonchalantly. By doing so, you have inadvertently cursed this repo to be haunted by that vile creature forevermore.

**Comment by DerpyCoder21** [comment]
its ok anyooing dog ate him
