### ISSUE TITLE
[1.12.2] Broken JEI Support

### ISSUE THREAD

**Issue by TheLimePixel** [PaleoCrafter/VanillaImmersion#27]
Well, I'm surprised that this hasn't been mentioned yet as it's been an issue for a good while. Basically, the search bar doesn't update (it stays as a single white horizontal line), but you can still type to search for stuff.

**Comment by marvin-roesch** [comment]
Hm, could you provide me with a screenshot of what you mean? I'm not doing anything special with the search (except auto-focusing it) and can't see any issues with it in my environment.

**Comment by TheLimePixel** [comment]
As you can see, I have searched for Cobblestone and the search bar remains the same:
![image](https://user-images.githubusercontent.com/25333164/34412519-06017390-ebde-11e7-82ac-84ee6d6d841d.png)

**Comment by marvin-roesch** [comment]
Interesting...

I'm going to release a new build reasonably soon (probably today) with an updated dependency on JEI. Let's hope it'll work then, as it does for me in the dev environment.
