### ISSUE TITLE
Freezing upon world startup - incompatibility with 'Better with Mods'

### ISSUE THREAD

**Issue by ChiefLogan3010** [PaleoCrafter/VanillaImmersion#29]
I'm having an issue with this mod where it freezes the game upon a world load, since there is no crash log it's hard to determine whether this is an incompatibility error or something else, I have attached the latest log however. Worlds load perfectly fine without VI present.

[latest.log](https://github.com/PaleoCrafter/VanillaImmersion/files/1647954/latest.log)

**Comment by shootHug** [comment]
I have the same issue, the world loading gets freezed.
have you found a solution for this problem?

**Comment by shootHug** [comment]
I found the problem: 
- incompatibility with `Better with Mods`
you have to disable all changes to Brewing stands and Enchanting, ev. Anvil... in Better with Mods.
i hope this solves your issue

**Comment by marvin-roesch** [comment]
Existing worlds that have had this issue before might still experience it, unfortunately. My attempt to properly migrate non-overrides to overrides seems to have corrupted the `level.dat` file. I removed that code, as migration should not be necessary anymore, anyways.
