### ISSUE TITLE
Incompatibility with 'Better with Mods'

### ISSUE THREAD

**Issue by shootHug** [PaleoCrafter/VanillaImmersion#30]
The changes in Better with Mods:
- Brewing Stands
- Enchanting Table
- Anvil
have to be desabled.. 
without this, the game will freeze in the loading screen.

**Comment by marvin-roesch** [comment]
Could you provide me with the following information:
- Version of this mod used
- Version of BWM used
- Changes in the BWM configuration from the default

With latest Better With Mods for 1.12.2, I cannot reproduce this issue in my development environment  right now.

**Comment by marvin-roesch** [comment]
Closing this as a duplicate of #29.
