### ISSUE TITLE
Placing an Anvil results on a temporal null block

### ISSUE THREAD

**Issue by Kevadroz** [PaleoCrafter/VanillaImmersion#35]
Version: 2.0.3.1
It appears on singleplayer, and the block is useless until the error dissapears.
The error dissapears on chunk reload.
May be a server-side error, because i tried to do a 'testforblock <coords> anvil' and didn't match.

**Comment by marvin-roesch** [comment]
Please provide me with your latest `debug.log` file and a complete mod list.

**Comment by Kevadroz** [comment]
It stopped happening, probably because some mods updated.
Also probly was fault of mods like texfix.

**Comment by marvin-roesch** [comment]
Thanks for information. For future reference, check back on your created issues and close them yourself when they are fixed.

**Comment by Kevadroz** [comment]
I just noticed that the anvil worked about an hour ago.
