### ISSUE TITLE
0.0.5.1 crashes dedicated forge server 1.9.4 build 1922 on startup

### ISSUE THREAD

**Issue by kreezxil** [PaleoCrafter/VanillaImmersion#4]
Issue: Vanilla Immersion 0.0.5.1 crashes dedicated forge server 1.9.4 build 1922 on startup

crash report:
https://gist.github.com/409d17b5142c01ee8d4741a22f40c15a

fml server latest:
https://gist.github.com/095946c66cf54cbefa65a431b16bc755

**Comment by litosns** [comment]
I got the same result. 0.0.5.1 crashes with latest forge.

**Comment by PaleoCrafter** [comment]
This issue appears to be related to the shadowing of the Kotlin libraries. That language really is causing me nothing but trouble with my builds, should have sticked to Scala xD

**Comment by PaleoCrafter** [comment]
Version 0.0.5.2 should run fine in production environments now. As you can see from the commit message, I disabled relocation of some files which **might** lead to name clashes with other mods shading Kotlin. I personally blame either Kotlin for being hard to shade or the shadow plugin for changing things it should not.
