### ISSUE TITLE
[Info Request] Anvil Gui

### ISSUE THREAD

**Issue by ghost** [PaleoCrafter/VanillaImmersion#40]
What GUI class is invoked when renaming something in an anvil with this mod? I use the blur mod and I need to add the class for the anvil GUI to it's blacklist.

**Comment by marvin-roesch** [comment]
The GUI class is `de.mineformers.vanillaimmersion.client.gui.AnvilGui`.

I might see about integrating with Blur myself, then users won't have to manually add it to the blacklist.

**Comment by ghost** [comment]
Thank you very much :)

**Comment by ghost** [comment]
Finally got around to retesting this, it doesn't appear to work. I've tried poking it too, it just won't work.

**Comment by ghost** [comment]
Using a J VisualVM heap dump I was able to find the correct class: de.mineformers.vanillaimmersion.client.gui.AnvilTextGui

Issue resolved, closing.
