### ISSUE TITLE
Crash with shader

### ISSUE THREAD

**Issue by Drehverschluss** [PaleoCrafter/VanillaImmersion#5]
This Crash happens when i break the Crafting Table with a active shader.
http://pastebin.com/3THf33r4

Just to let you know its the KUDA-Shaders v6.2.81 - Default -> http://www.minecraftforum.net/forums/mapping-and-modding/minecraft-mods/1293662-kuda-shaders-v6-2-81-update-april-2nd-2016

**Comment by PaleoCrafter** [comment]
Thanks for reporting this issue, I would have never found out about it myself!

I was able to reproduce it and it appears that the shader mod ist doing something weird to the rendering of Tile Entities, causing them to still render when the underlying block is gone already. While I can fix this with a few checks at the right places, I'll have to investigate this further to assure this is actually an issue on the Shader Mod's side, not mine.
