### ISSUE TITLE
non lan host kick from world sometimes 

### ISSUE THREAD

**Issue by monkeybee11** [PaleoCrafter/VanillaImmersion#9]
ive ran in to a thing that kicks me form a "open to lan" world that im not hosing

using somethings like the [?] on the crafting table  and hitting a enchant book on the anvil with a hammer 

 

seeing it just kicked me form the "lan" world im not able to find a crash report  sry hoping u can reproduce it :(

if im ever able to find the error log ill post it asap

**Comment by darthvader45** [comment]
Did you try on a world that's not open to lan?

**Comment by monkeybee11** [comment]
no but it seems to be fixed in newer verions of the mod

**Comment by darthvader45** [comment]
That's good, so this can be closed.
